name: Deploy
on:
  workflow_dispatch:
    inputs:
      cluster-name:
        description: 'Build Cluster'
        required: true
      namespace:
        description: 'Build ENV'
        required : true
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1


      - name: Checkout private
        uses: actions/checkout@v3
        with:
          repository: Swasth-Digital-Health-Foundation/DevOps
          ref: 'workflow'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: recursive
          path: DevOps

      - name: Check file structure
        run: ls -lrt ${{ github.workspace }}

      - name: 'Deploy'
        uses: bitovi/github-actions-deploy-eks-helm@v1.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          cluster-name: ${{ github.event.inputs.cluster-name }}
          name: 'demo-app'
          namespace: ${{ github.event.inputs.namespace }}
          chart-path: 'application/helm/core/demo-app/'
          config-files: 'application/helm/core/demo-app/values.yaml, DevOps/hcx/ansible/inventory/dev/group_vars/dev.yaml' #, https://github.com/Swasth-Digital-Health-Foundation/DevOps/blob/workflow/hcx/ansible/inventory/dev/group_vars/dev.yaml'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'




